# -*- coding: utf-8 -*-
"""ICS-3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XH4U6g68suGvFqe61zmey2t7cKw9gyI3

DIFFIE-HELLMAN KEY EXCHANGE
"""

### PUBLIC KEYS
P = 17
G = 27

### PRIVATE KEYS
a = 13
b = 9

### GENERATE KEYS
x = (G ** a) % P
y = (G ** b) % P
print(f'Generated Keys - x: {x}, y: {y}')

### GENERATE SECRET KEY WITH x AND y
key_a = (y ** a) % P
key_b = (x ** b) % P
print(f'Generated Secret Keys - KEY-A: {key_a}, KEY-B: {key_b}')